### ISSUE TITLE
CustomRP Crashing

### ISSUE THREAD

**Issue by danielsartor** [maximmax42/Discord-CustomRP#1]
I was trying to create a custom detail for the custom RP and I was getting and error of max length, but if I click continue it works fine to edit again, but I clicked quit by mistake and it closed. After that I couldn't open the .exe, it starts on the windows tray but instantly crashes (if I hover my mouse over the icon it disappears). I've restarted my computer and deleted the folder, also tried to user another folder with new files.

**Comment by maximmax42** [comment]
~~Oh my god people actually use my software.~~

Alrighty, I was able to recreate the problem, will roll out an update within about half an hour.
For now, open the `%localappdata%\maximmax42` folder (copy and paste it in either Win+R window or in the File Explorer address bar), then there will be `CustomRP.exe_blablabla` folder, and there will be `user.config` file.
Open with whatever text editor you have, find the `<setting name="details" serializeAs="String">` line, and right under it, either delete all the text within `<value></value>` or shorten it to less than 128 characters.
Save, and start the app again.

**Comment by danielsartor** [comment]
Hey, congratulations for your. My friends are using and recommended it to me, it's not heavy as the others and it works great :D.

I was able to fix by changing the file names. I did it before I saw your reply. Also thank you for the quick reply! :D
![image](https://user-images.githubusercontent.com/1349833/54229943-1cec6f00-44e4-11e9-9afd-ee08cb01e484.png)

Btw, are there options to change the message "Playing" to other things? Like "Developing" "Jumping" or other things?

**Comment by maximmax42** [comment]
Well, if you'll want to use the app with the original name again, you will still have to delete that whole  `%localappdata%\maximmax42\CustomRP.exe_blablabla` folder. Although, I'm not sure, because every time I change the app version, settings are getting reset apparently.

And no, that's unfortunately the limitation of Discord and there's nothing I can do, just like with the  "elapsed" and "remaining" text on the time part of the presence.

**Comment by danielsartor** [comment]
Awesome!
I found the folder and I've deleted it. I will redo the settings later and use the original name. Thank you again for your support! o/

**Comment by maximmax42** [comment]
You're welcome~
And here's the fixed program that doesn't allow you to exceed 128 characters in the text fields and 32 characters in the key fields: https://github.com/maximmax42/Discord-CustomRP/releases/tag/1.3
