### ISSUE TITLE
Linux/Mac Support

### ISSUE THREAD

**Issue by mmccall0813** [maximmax42/Discord-CustomRP#10]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
Multi-OS support (Linux/Mac)

**Describe alternatives you've considered**
I havent considered any alternatives as of now

**Additional context**
Im on linux and would love to see support for it along with other operating systems

**Comment by maximmax42** [comment]
Well the thing is, this app is written on a Windows-only library, so if I want to make Linux and Mac versions I'd have to rewire the whole thing, so probably not happening, at least for now. It should work with Wine tho.

**Comment by mmccall0813** [comment]
> It should work with Wine tho.
Tried in Wine, it instantly crashes.

**Comment by maximmax42** [comment]
https://github.com/ThatOneCalculator/DiscordRPCMaker
This one should work in Linux.
(ignore me opening-closing the issue, I keep misclicking the button)
