### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by robloxgamergithub** [maximmax42/Discord-CustomRP#114]
how to open that program but it not **### _working_** and not opening but how do i open it

**Comment by maximmax42** [comment]
Does it not install at all or does it not open after installing?

**Comment by robloxgamergithub** [comment]
it doesnt open after installing when i already accidentally clicked close button

**Comment by maximmax42** [comment]
Delete `%localappdata%\maximmax42` folder, download latest version, install it, launch, when it asks for analytics, say no. Or you can try to say yes, and if it doesn't work, kill the app, delete the folder again, launch the app but say no.

**Comment by robloxgamergithub** [comment]
it says that program isnt an file
![image](https://user-images.githubusercontent.com/95968788/162793690-efb887c1-2923-4266-b43f-df31e09d931d.png)

**Comment by robloxgamergithub** [comment]
![image](https://user-images.githubusercontent.com/95968788/162793804-ac6fcf2f-554a-4a90-9b9a-639261baf34a.png)

**Comment by maximmax42** [comment]
> ![image](https://user-images.githubusercontent.com/95968788/162793804-ac6fcf2f-554a-4a90-9b9a-639261baf34a.png)

Well, that's because I'm a single developer, because of that I don't have a special code signing certificate to let computers trust my software. Although it will be trusted once enough people will install this version.

Anyway, great that it works now.
