### ISSUE TITLE
Buttons Arent Opening in browser

### ISSUE THREAD

**Issue by stationswift001** [maximmax42/Discord-CustomRP#115]
**Describe the bug**
when I set a presence with bttons and I click the buttons, they dont open the set links in the browser

**To Reproduce**
1. Go to buttons
2. set a link and title
3. go to discord
4. click on button
5. nothing happens

**Expected behavior**
the buttons arte supposed to open linbks, right?
**Screenshots**

**Useful Info**
 - Windows Version: Windows 10
 - Application Version: latest

**Comment by MasterCubo** [comment]
If the buttons are on your own status, you can't click them yourself. It's a discord bug. Ask someone else to test them, or click on them with another account if you have one. I ran into the same question myself a few months ago.
