### ISSUE TITLE
huh im sorry how do i delete that one?

### ISSUE THREAD

**Issue by Kr1nxx** [maximmax42/Discord-CustomRP#117]
**BEFORE POSTING**
Please check https://github.com/maximmax42/Discord-CustomRP/wiki/FAQ for a possible solution. If it's not there, then carry on with creating an issue ticket.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Useful Info**
 - Windows Version: [e.g. Windows 7, Windows 10 2004]
 - Application Version: [e.g. 1.8]

**Additional context**

**Comment by Kr1nxx** [comment]
how do I delete? im upset :((

**Comment by maximmax42** [comment]
I think only I can delete the issues. But it's not necessary anyway.
