### ISSUE TITLE
CustomRP doesn't show pictures

### ISSUE THREAD

**Issue by Kr1nxx** [maximmax42/Discord-CustomRP#118]
I'm trying to make my rich presense show images but somehow I made a mistake and reuploaded many times and now CustomRP doesn't show images on discord anymore.
I tried creating another application and adding pictures but the result is the same...?

How can I fix it?
![image](https://user-images.githubusercontent.com/104755180/166200620-25ab65af-6f3c-4fc4-bf83-5da774dc4d9f.png)
![image](https://user-images.githubusercontent.com/104755180/166200982-27a7fdf7-f0e2-40b7-9083-cdb2920aef39.png)

**Comment by Kr1nxx** [comment]
uhhhh...? some pictures I uploaded yesterday, it disappeared and today it came back and it's on discord, but it's not the picture I want so I have to wait?
![image](https://user-images.githubusercontent.com/104755180/166201220-a31bb33f-9b93-43fa-bcf4-7a5a13ff1345.png)

**Comment by Kr1nxx** [comment]
yea... actually yes you just have to wait btw))) ask discord im not good at "pc things"

**Comment by maximmax42** [comment]
Sooo is the problem fixed now?

**Comment by Kr1nxx** [comment]
> Sooo is the problem fixed now?

I think so
