### ISSUE TITLE
can i install this on a mac?

### ISSUE THREAD

**Issue by denzven** [maximmax42/Discord-CustomRP#12]
i have a friend that loved this repo but sadly there is only an exe.. how can he run this on a mac?
(this is my first time writing stuff on github if this is the wrong place to ask pls tell)

**Comment by maximmax42** [comment]
My program is written with a Windows only framework sadly, so it wouldn't be possible to natively run on Linux or Mac. You could try to run it via Wine, but honestly you're better off using some other application, like https://github.com/ThatOneCalculator/DiscordRPCMaker.

**Comment by denzven** [comment]
> 
> 
> My program is written with a Windows only framework sadly, so it wouldn't be possible to natively run on Linux or Mac. You could try to run it via Wine, but honestly you're better off using some other application, like https://github.com/ThatOneCalculator/DiscordRPCMaker.

thx!
