### ISSUE TITLE
Some antivirus engines detect DiscordCustomRP as malware.

### ISSUE THREAD

**Issue by ItsJustLag** [maximmax42/Discord-CustomRP#13]
So I downloaded the latest release from GitHub and did a scan of it in VirusTotal to see if it was malware. A few low-level antivirus engines detected it, so I guessed it was just a false positive. I ran the file and Kaspersky System Watcher terminated the application, deleted some stuff like the executable in my downloads folder, and asked for an advanced disinfection. I'm not sure if this is malware or not, but just letting the devs know. It's also not signed which made Microsoft Defender SmartScreen detect it. https://www.virustotal.com/gui/file/5b7f9ee3fa09f228dc8ae0995a27be28a6bd74a7e9f1a149465325bdded849bb/behavior/Microsoft%20Sysinternals%20Sysmon

![image](https://user-images.githubusercontent.com/80059602/119504099-a68d5d80-bd39-11eb-9ca9-8d79d33656b4.png)

**Comment by maximmax42** [comment]
Yeah, a false-positive, most likely caused by my app not being signed. Cheapest certificate costs like $160/yr, and for an app that makes $0, that's a huge investment.
