### ISSUE TITLE
The RichPresence stops working after windows sleep

### ISSUE THREAD

**Issue by guanaco0403** [maximmax42/Discord-CustomRP#132]
**Describe the bug**
after I put my computer to sleep, and I turn it back on, discord no longer displays activity and I have to click on "Disconnect" then "Connect" so that the activity reappears.

**To Reproduce**
1. put windows in sleep mode
2. turn it back on
3. go to your discord and check your activity

**Expected behavior**
that the activity continues to operate.

**Useful Info**
 - Windows Version: [windows 11]
 - Application Version: [1.15.1]

**Comment by maximmax42** [comment]
Huh. That's an interesting one. Does CustomRP stay blissfully unaware that it's not connected anyway?

**Comment by guanaco0403** [comment]
mhh wierd..., it stays "connected" but the discord doesnt show the activity, btw I restarted my computer and it looks like that now its working soo... i think it fixed by itself

**Comment by maximmax42** [comment]
Hm. Maybe it's some Windows quirk. I'm not even sure what I can do here. I think the app is supposed to ping Discord every now and then and check for a connection status anyway.

**Comment by 2vsh** [comment]
Interesting, when I tried to replicate this just out of curiosity it behaved as intended. Either this was fixed, or is a specific unrelated program that's downloaded causing this behavior?

**Comment by maximmax42** [comment]
Well I didn't do anything to even try and fix it, so... probably Windows being Windows.

**Comment by maximmax42** [comment]
Comment or create new issue if it happens again.
