### ISSUE TITLE
I can't connect.

### ISSUE THREAD

**Issue by KGplayzMC** [maximmax42/Discord-CustomRP#138]
I downloaded the app and it won't let me connect at all. It keeps saying: "connection failed (is discord running?)". Please help me connect.
![Screenshot 2022-07-19 025549](https://user-images.githubusercontent.com/84199822/179685820-997e5998-7778-442b-9930-4c7097f63c2d.png)

**Comment by maximmax42** [comment]
https://github.com/maximmax42/Discord-CustomRP/wiki/FAQ#the-app-says-wrong-idis-discord-running-or-connects-indefinitely-even-though-im-sure-i-did-everything-right-and-discord-is-running
