### ISSUE TITLE
The app disappears and I can't edit anything

### ISSUE THREAD

**Issue by KahpotVanilla** [maximmax42/Discord-CustomRP#14]
Hello, I know it sounds stupid but when I open the CustomRP App after I close it, It just disappears and its working on my pc.
at the start it worked but now I can't open it but the status works (I guess)
how can I edit it now?

**Comment by maximmax42** [comment]
It minimizes into the app tray, the one on the left of the taskbar, probably after you press an arrow to show all.
![image](https://user-images.githubusercontent.com/2225711/121563159-9791f500-ca33-11eb-8ca3-8e39ab79e0bc.png)
