### ISSUE TITLE
When I play a game, the activity is overwritten with the game i'm playing for others.

### ISSUE THREAD

**Issue by Mystery24601** [maximmax42/Discord-CustomRP#153]
**Describing the bug**
So this bug is more of a conflict which occurs whenever you play a game and also occurs the same way whenever you play a game that doesn't get registered as one on discord. (While having CustomRP in the background or as a window on your screen)

The last option (playing a game that doesn't get registered as one on discord) makes this a much more annoying conflict as it makes it impossible to get rid of the game from your activity until you close the game.

**To Reproduce**
Steps:
1. Open Discord, Discord on Web on an alt account (or another instance of Discord) and CustomRP.
2. Press "Update Presence" button in CustomRP once you've set a description, etc. (No specifics, just a valid presence for Discord to place on your profile)
3. Open any game that doesn't get registered by Discord. (You can find Registered Games from the settings)
4. If done, you will see your activity change from the alt account's perspective despite having CustomRP active in the background.

**Expected behavior**
You would see CustomRP's Presence instead of the game you've opened.

**Unexpected behaviour**
Normally, you would expect that CustomRP is being prioritized to place the presence information onto your profile, but this gets replaced with the "game that doesn't get registered by Discord" instead. You and others can see them both, but only when you press "Profile" on the main user. I've only tested this on the game "Attorney Online", which is the only one (so far) that didn't appear in the "Registered Games" list on Discord, but did show on my profile.

**Screenshots**
Before playing Attorney Online:
![image](https://user-images.githubusercontent.com/111801929/186015044-0b71cb42-5407-4027-a8b5-5ba3d10dc2a0.png)

After playing Attorney Online:
![image](https://user-images.githubusercontent.com/111801929/186015254-13718ef9-6bc6-4819-881c-9241f41c7ca3.png)

**Useful Info**
 - Windows Version: Windows 10 Version 2009
 - Application Version: 1.16.5

**Additional context**
I got on the discord server to discuss this issue and the latest response was to make a Github account just to submit this issue.
Other than that, one person stated that you could also update the presence each time it changes but that is only a temporary fix.

**Comment by maximmax42** [comment]
Summary of the Discord conversation on that topic:
At first I thought I have no control over what presence would be shown, but it seems that Discord shows whatever was updated most recently. That means if I were to implement a once in some period automatic presence update, it would guarantee for it to be the preferred presence. That would work well with games that have no Rich Presence, not so well with games that do. So I'm not even sure it's worth implementing.

**Comment by Mystery24601** [comment]
I'll consider this issue closed.
