### ISSUE TITLE
"Wrong ID"

### ISSUE THREAD

**Issue by mannyok** [maximmax42/Discord-CustomRP#154]
It says wrong ID whenever I try and connect the rich presence and I tried all the stuff in the FAQ but none of them worked. What do I do?

**Comment by maximmax42** [comment]
Reinstalling BD if you have it didn't help? Running as admin didn't help? Adding CustomRP to exceptions and **restarting PC** didn't help either?

**Comment by mannyok** [comment]
Yeah i tried all of them and it didn't work

**Comment by mannyok** [comment]
I removed a button link and it's working now... So does this mean I can only have 1 button?

**Comment by maximmax42** [comment]
Wait what. Can you give me the URL you tried?
