### ISSUE TITLE
The app sometimes disconnect the Application which will result a manually reconnect 

### ISSUE THREAD

**Issue by KahpotVanilla** [maximmax42/Discord-CustomRP#16]
Hello, the app sometimes disconnect the Discord application and I don't get notice about it, if it disconnect I have to manually reconnect it by opening the app manually, if there will be an auto reconnect when you lost connection it would be nicely.
Here is a screenshot that shows the issue:
![Screenshot_1](https://user-images.githubusercontent.com/85695775/122547343-a6326a80-d038-11eb-81dd-48f15b9bc9aa.png)

**Comment by maximmax42** [comment]
Hm... I'll try to come up with something.
In the meantime, there's an option to reconnect from the context menu on tray icon, so you don't need to open the app completely.

**Comment by maximmax42** [comment]
Oops, forgot completely. 1.10.1 has been released yesterday, should auto reconnect now.
