### ISSUE TITLE
Bug Rich Presence

### ISSUE THREAD

**Issue by BenMagNiemanden** [maximmax42/Discord-CustomRP#163]
**Describe the bug**
Other games cover the rich presence for othe discord users

**To Reproduce**
just use the software how you should

**Expected behavior**
Just show the rich presence.

**Screenshots**

**Useful Info**
 - Windows Version: 10

**Comment by maximmax42** [comment]
Discord shows whatever presence was updated last. So if your game doesn't have RP, then you can just update presence in CustomRP and it'll be on top. But if the game has RP, nothing you can do really.
