### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by 2latemc** [maximmax42/Discord-CustomRP#166]
**Describe the bug**
The app says its succesfully connected, however its not showing up on my Discord. It worked previously, now after reinstalling Windows its not working anymore. I already reinstalled Discord and removed all third-party clients.

**Comment by maximmax42** [comment]
Did you enable this: ![image](https://user-images.githubusercontent.com/2225711/188219661-49713f90-fa76-4645-b04a-fc1bc0f029bd.png)

**Comment by 2latemc** [comment]
> Did you enable this: ![image](https://user-images.githubusercontent.com/2225711/188219661-49713f90-fa76-4645-b04a-fc1bc0f029bd.png)

That fixed it, i feel very stupid now :D Sorry for that! Love your app btw!
