### ISSUE TITLE
Doesn't Work After Restarting PC

### ISSUE THREAD

**Issue by EsmaHex** [maximmax42/Discord-CustomRP#169]
**Describe the bug**
When I start up CustomRP after turning my PC on for the day, it says it's connected, but nothing is displayed on my profile. Restarting Discord and CustomRP hasn't helped and even disconnecting for a time before reconnecting hasn't helped either. "Display current activity as a status message" is enabled.

**To Reproduce**
1. Get Custom RP set up
2. Shut off the PC for the night or just reboot
3. Reboot pc
4. Open Custom RP after Discord boots up
5. See that it's connected but won't display on Discord

**Expected behavior**
For it to connect as intended and not have to fight with it every morning to somehow get it to work.

**Useful Info**
 - Windows Version: Windows 10

**Comment by maximmax42** [comment]
Can't reproduce. I have CRP on startup and it works every time. Do you have BetterDiscord?

**Comment by EsmaHex** [comment]
I do have BetterDiscord, does it by chance mess with CustomRP?

**Comment by maximmax42** [comment]
Yeah, it might. Although usually it just doesn't let CRP work at all, this is the first time I see this kind of behavior.

**Comment by EsmaHex** [comment]
Could it be due to the recent updates that temporarily broke BetterDiscord? I don't have any plugins in use if that helps.

**Comment by maximmax42** [comment]
I have no idea how exactly BD is interfering, I just know that if you uninstall it, run CustomRP at least once, and install BD back, everything goes back to normal.

**Comment by EsmaHex** [comment]
I've actually tried that and it worked, but after restarting my PC, it goes back to this behavior. Sometimes it works, usually after updating a theme or something, but most of the time, it doesn't work at all.

**Comment by maximmax42** [comment]
Hm. I honestly have no idea how to fix that. Like, I don't even understand why or how BD screws with my app.

**Comment by EsmaHex** [comment]
I understand that. Thanks for taking the time to review my issue. I hope you have a good day.

**Comment by EsmaHex** [comment]
Minor Update: After updating Custom RP to the version from 2 days ago, it worked until the computer was restarted again. Afterward, it went back to this strange behavior.

**Comment by maximmax42** [comment]
Hm. This probably won't solve it, but it won't hurt to try.
Open cmd as admin and run `sfc /scannow`, and if you're on Win8+, also run `DISM /Online /Cleanup-Image /RestoreHealth`.

**Comment by EsmaHex** [comment]
This didn't seem to work, but after reinstalling Discord, it seems to be working, granted I have to restart Discord a few times before it sees CustomRP with BetterDiscord, but without it, it works perfectly.
