### ISSUE TITLE
Change the emoji format

### ISSUE THREAD

**Issue by KahpotVanilla** [maximmax42/Discord-CustomRP#17]
Hey Max, I have a suggestion, or maybe it will be cool.
When you type in an emoji, its just black and white, I can't see which emoji am I typing in the text box. so, I want you to change the format of the emojis to be colored and not just black and white, I hope my suggestion will be approved !
and again, thank you so much for making this application !! I love your work !
![image](https://user-images.githubusercontent.com/85695775/122921658-6686be00-d36b-11eb-8e36-8a7b26ec4070.png)

**Comment by KahpotVanilla** [comment]
something like this but I hope you will understood

**Comment by maximmax42** [comment]
Sadly I can't find any way of implementing that with the built in tools. There is one external library, but it's a part of a big pack and costs $1000. So, can't implement sadly.
