### ISSUE TITLE
Not connecting to discord, happened after update to 1.16.10

### ISSUE THREAD

**Issue by TheCreatorrr333** [maximmax42/Discord-CustomRP#170]
**BEFORE POSTING**
Please check https://github.com/maximmax42/Discord-CustomRP/wiki/FAQ for a possible solution. If it's not there, then carry on with creating an issue ticket.

**Describe the bug**
Program not working, showing `Connection failed (Is discord running?)` in bottom right corner. After updating to 1.16.10 the app started behaving like that. There are no errors shown besides the connection failed. My discord is running of course. I double and triple checked if the client id is correct - and it is.

**To Reproduce**
1. Download CustomRP 1.16.10
2. Set up rich presence
3. Watch app show the error instead of rich presence being displayed in discord

**Expected behavior**
App should display rich presence within discord, instead it shows error and the client id field goes red, i did not change its configuration after updating to 1.16.10 and it worked before on this exact config.

**Screenshots**
![main window](https://user-images.githubusercontent.com/106310501/198389920-09b010c5-aef9-453c-8064-748b6c57f1dd.png)
![about window (app version)](https://user-images.githubusercontent.com/106310501/198389985-54bb6767-1ec5-4d83-9618-ac2099633e5a.png)

**Useful Info**
 - Windows Version: Windows 10 21H2 (OS Build 19044.2006)
 - Application Version: 1.16.10

**Additional context**
Happened after i updated the app when prompted to do that from 1.16.9 to 1.16.10

**Comment by maximmax42** [comment]
Try adding the app to the firewall and/or antivirus exceptions. Maybe it stopped working because it deemed the newer version to not be safe or something.

**Comment by TheCreatorrr333** [comment]
It still doesn't seem to work...

**Comment by maximmax42** [comment]
Don't forget to reboot PC after that.

**Comment by TheCreatorrr333** [comment]
Ok it actually worked, thanks!
