### ISSUE TITLE
CustomRP not opening in any way

### ISSUE THREAD

**Issue by mrfancycorgi** [maximmax42/Discord-CustomRP#183]
Hello! I got recently introduced to the program, and i tried to give it a try. But, whenever i try to open the application, it doesn't work. It doesn't appear for a split second, it doesn't appear on task manager, my antiviruses are all turned off; there is, as i can say, no reason as to why it won't open.

Opening it on the desktop shortcut? Nothing. Running as administrator? Nothing; I've even tried going to '%appdata%\CustomRP' to open the exe by there, but still nothing

I browsed through past issues here and, while i found similar bugs, i read them all and nothing helped.

**Useful Info**
 - Windows Version: Windows 10
 - Application Version: 1.16.12

https://user-images.githubusercontent.com/69689429/203867082-90a1af5e-a343-4132-b400-cea9f9fb1aad.mp4

Here's a quick video i recorded trying to demonstrate the issue.

**Comment by mrfancycorgi** [comment]
I have two monitor screens; when opening it for the first time, i thought that was the issue [that the program opened in the other monitor, other than my main], but, as you can see, the icon doesn't appear on the task bar.

**Comment by maximmax42** [comment]
Hm. It never opened even once?

**Comment by mrfancycorgi** [comment]
I will try again when i wake up tomorrow, maybe i have to restart the PC

**Comment by mrfancycorgi** [comment]
> Hm. It never opened even once?

Nope, not for one second. As soon as i realized the program wouldn't start, i got here to try and search for anything that could help me

**Comment by maximmax42** [comment]
Is .NET Framework 4.8 installed? https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer

**Comment by mrfancycorgi** [comment]
> Is .NET Framework 4.8 installed? https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer

this is kinda weird, that exe is a setup installer, right? well, it won't open too. maybe it's just my PC and i'll have to restart it. when i launch it again tomorrow i'll see if i got any results.

**Comment by maximmax42** [comment]
Yeah, it's an installer. If this doesn't work, try https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-offline-installer

**Comment by mrfancycorgi** [comment]
> Yeah, it's an installer. If this doesn't work, try https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-offline-installer

i'm back and no, that one won't download either.

**Comment by maximmax42** [comment]
Well. Something with your Windows install, probably.

**Comment by maximmax42** [comment]
Comment if you have any updates on the situation.
