### ISSUE TITLE
crp not working after recent discord update

### ISSUE THREAD

**Issue by theguy2** [maximmax42/Discord-CustomRP#186]
after the most recent discord update my crp only says "Connecting..." and doesnt connect at all, i can stop it by doing disconnect and try again but same result. even tried reinstalling but same result, im out of options i think

**Comment by maximmax42** [comment]
Have you tried steps in FAQ? https://docs.customrp.xyz/faq

**Comment by theguy2** [comment]
oh it works now thanks
