### ISSUE TITLE
Cant uninstall.

### ISSUE THREAD

**Issue by IlyasStuff** [maximmax42/Discord-CustomRP#187]
**BEFORE POSTING**
Please check https://github.com/maximmax42/Discord-CustomRP/wiki/FAQ for a possible solution. If it's not there, then carry on with creating an issue ticket.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Useful Info**
 - Windows Version: [e.g. Windows 7, Windows 10 2004]
 - Application Version: [e.g. 1.8]

**Additional context**

**Comment by maximmax42** [comment]
Quit the application first. It's in the tray.

**Comment by IlyasStuff** [comment]
> Quit the application first. It's in the tray.

I tried,but it keeps reopening when i go to uninstall it.

**Comment by maximmax42** [comment]
You quit the application by going File -> Quit or right clicking the icon in the tray and picking Quit, not by just pressing X.

**Comment by IlyasStuff** [comment]
> You quit the application by going File -> Quit or right clicking the icon in the tray and picking Quit, not by just pressing X.

Thanks.
