### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by hack3xx** [maximmax42/Discord-CustomRP#188]
hi i am facing a problem. when I run the program, an error appears (screenshot) and it does not start.
I ran with installed version and portable, doesn't work
.net framework 4.8 installed

![2022-12-06_14-53-19](https://user-images.githubusercontent.com/119933224/205891126-4b5ad45a-bad1-4995-9f02-86aeebd09a48.png)

**Useful Info**
 - Windows Version: Windows 7 86x
 - Application Version: 1.16.13

**Comment by maximmax42** [comment]
А доходит до вопроса "разрешить аналитику" или нет?

**Comment by hack3xx** [comment]
и что никак не исправить?

**Comment by maximmax42** [comment]
Обновить винду, ну или попробовать более старую версию CustomRP, например https://github.com/maximmax42/Discord-CustomRP/releases/tag/1.16.12.
