### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by yash1441** [maximmax42/Discord-CustomRP#19]
**Describe the bug**
Custom RP is not able to connect to my profile after game activity occurs. (1.10.1)
It tries reconnecting every 5 seconds fine but never successfully.
I didn't change any settings and rechecked everything to be correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/14055917/123664035-9d217480-d854-11eb-80cb-cfa2ce1cddac.png)

**How to fix**
Refresh (Ctrl + R) discord.
I think it has something to do with the game activity. After I exit the game and the game activity goes away, Custom RP should be able to display the rich presence but it doesn't.

**Comment by maximmax42** [comment]
Yeah, apparently it's a widespread thing. Thing is, I haven't changed anything in regard of connection, so I have no clue why it's doing this all of a sudden.
You can try closing both Discord and CustomRP, then give it like a couple of seconds, and then launch Discord, then CustomRP and try to connect, should work.

**Comment by maximmax42** [comment]
I'll mark it as unfixable for now, but I'll try some things.

**Comment by maximmax42** [comment]
Could you test it again on a newest version?

**Comment by MorsHs** [comment]
![image](https://user-images.githubusercontent.com/77497581/128587217-7ec33a66-0600-4ffa-a60a-7bd8eb31c051.png)

Is ur Activity Status enabled? because i disabled it and its stuck on a loop where it ways "Connecting"

**Comment by LuisPavelA** [comment]
It still does not work :(

**Comment by LuisPavelA** [comment]
@maximmax42

**Comment by maximmax42** [comment]
@LuisPavelA Do you have the same problem as OP? Infinite connection? Or something different?

**Comment by LuisPavelA** [comment]
@maximmax42 My Rich Presence is not showing up

**Comment by maximmax42** [comment]
What error does it show in the app?

**Comment by LuisPavelA** [comment]
@maximmax42 It does not show me any errors

**Comment by maximmax42** [comment]
So it's just connecting indefinitely? In that case, check if activity status is enabled in discord settings.

**Comment by LuisPavelA** [comment]
@maximmax42 I have it enabled and it still does not work

**Comment by maximmax42** [comment]
Try restarting both Discord and CustomRP (file - exit), then relaunching everything again. If that doesn't help, I don't know what will, especially since you say there are no errors.

**Comment by LuisPavelA** [comment]
It worked! @maximmax42

**Comment by maximmax42** [comment]
Oh hey, nice.

**Comment by MasterCubo** [comment]
Hey uh, having a similar problem with connection, says wrong ID, ive checked and even made a new application and stuff, still no connection. Restarted Discord, CustomRP, and my PC multiple times. Do we know why? I'm on the latest update, but this was happening before as well out of nowhere with no update. I *am* using the application ID. Can I do something when the Pipe screen comes up?

**Comment by MasterCubo** [comment]
It started happening when I added a lot of assets. 106 actually.

**Comment by maximmax42** [comment]
@MasterCubo Did it work before? If yes, I honestly have 0 clue what it can be. Try adding to firewall exceptions, go through all numbers from 0 to 9 in the pipe menu, maybe something will help.

And no there's no debug mode, but it's a good idea, I'll research on that.

**Comment by MasterCubo** [comment]
I added it through the firewall, and now its just "Connecting..." forever with no Pipe pop-up. I think it has to do with assets and that connecting. Because when I added those 100 assets, it stopped working, and when I reinstalled CustomRP it still didn't work.

**Comment by MasterCubo** [comment]
I made a new application with no assets, and I cleared all of the entry boxes except details and state. So the assets aren't the problem...

**Comment by MasterCubo** [comment]
Just as an update, whenever I added it to the Firewall I had to let the exe through by "adding another program". As in it didn't show up in the normal firewall bypass screen. I custom-added discord as well. That may do something weird? I'm no too sure

**Comment by MasterCubo** [comment]
> Yeah, apparently it's a widespread thing. Thing is, I haven't changed anything in regard of connection code, so I have no clue why it's doing this all of a sudden.
> You can try closing both Discord and CustomRP, then give it like a couple of seconds, and then launch Discord, then CustomRP and try to connect, should work.

I can check the patch notes to see if *Discord* updated some connection settings of some sort.

**Comment by maximmax42** [comment]
> I added it through the firewall, and now its just "Connecting..." forever with no Pipe pop-up. 
You need to ctrl-click on the connect button while disconnected for it to open up. Also if it's connecting indefinitely it might be actually working, but you do need to restart discord again.

**Comment by maximmax42** [comment]
Exit and relaunch.

**Comment by MasterCubo** [comment]
oh... it connected? Wow thats sad. I have no idea why so I cant help. Did you update something? If not all I did was Add the exe's for customRP and Discord through the firewall then restart both the programs and my PC. Maybe that can help anyone else with the problem. This is by far the best Custom Rich Presence software with its GUI and built in unix time stamp converterl, so I'm glad its working again :D

**Comment by maximmax42** [comment]
Wow, so this solution finally worked for someone! I guess I never told anyone to also restart both apps and/or Windows, maybe that was the reason.

**Comment by maximmax42** [comment]
Since there was no comment from the original poster, I'm closing the issue. Feel free to reopen if the problem persists.

**Comment by MareoLevis** [comment]
it didnt work, every thing appear but not in dis cored. i trie restart both but it seems this did not fix said issue.

**Comment by maximmax42** [comment]
> it didnt work, every thing appear but not in dis cored. i trie restart both but it seems this did not fix said issue.

Why are you posting in a closed issue from 2021.
https://docs.customrp.xyz/faq#the-app-says-wrong-id-is-discord-running-or-connects-indefinitely-even-though-im-sure-i-did-everythi
