### ISSUE TITLE
Connection Failed (Is Discord running?)

### ISSUE THREAD

**Issue by Satera1** [maximmax42/Discord-CustomRP#195]
I read the faq and tried some tips given there, like adding the CustomRP folder to the antivirus exceptions.
I've also tried running it in admin mode, it seems to "connect successfully", but the rich presence in my Discord profile doesn't change (perhaps indicating a false-connection?). I also left all options active in the discord settings, in the "Privacy in activities" tab.

Is there anything else I can try to resolve this issue?

**Comment by maximmax42** [comment]
Well uh, you should know if you have more than one account.

**Comment by Satera1** [comment]
Well, I have only 1 account logged into my discord app

**Comment by Satera1** [comment]
I only have the browser (firefox) and Blender running, I can try closing them to test

**Comment by Satera1** [comment]
> 

Yes, Discord application, not Discord Web

**Comment by maximmax42** [comment]
I'm honestly confused then. I don't think false connects are possible, so it's probably Discord being weird. Try restarting whole computer, idk.

**Comment by Satera1** [comment]
> I'm honestly confused then. I don't think false connects are possible, so it's probably Discord being weird. Try restarting whole computer, idk.

Ok, I'll try it now.
The strange thing is that it turns green, indicating that the connection was successful, but nothing changes

**Comment by Satera1** [comment]
Ok, I restarted my Pc and it works, finally, so I added some imagens and texts and it's all normal now. Thank u so much!
