### ISSUE TITLE
Malware Found

### ISSUE THREAD

**Issue by Shuja-Ahmed-Official** [maximmax42/Discord-CustomRP#198]
**BEFORE POSTING**
Please check https://github.com/maximmax42/Discord-CustomRP/wiki/FAQ for a possible solution. If it's not there, then carry on with creating an issue ticket.

**Describe the bug**
MALWARE FOUND

**To Reproduce**
1. Just open the App and close you will see.

**Expected behavior**
No Malware

**Screenshots**

**Useful Info**
 - Windows Version: [Windows 11 Pro 22H2]
 - Application Version: [e.g. 1.8]

**Additional context**
![Screenshot 2023-02-27 121939](https://user-images.githubusercontent.com/65089197/221499092-9ab45509-2775-4adf-8850-78ff8158b9b7.png)

**Comment by maximmax42** [comment]
God damnit Microsoft. Again.
There's no virus in my app, but defender really loves to believe there's this Wacatac. I've sent multiple versions of my app to them for analysis past couple months and they always found nothing and updated their database. It would work for 2-3 releases and then start again.

Can you give me the defender version? Should be in the settings or something.
