### ISSUE TITLE
ID is always wrong for no reason

### ISSUE THREAD

**Issue by pablogonzales2009** [maximmax42/Discord-CustomRP#20]
Every time I launch the program it tells me that the id is wrong, even though I keep copying the correct ID from the discord page.
![image](https://user-images.githubusercontent.com/66168769/128051293-42eac52e-6ce2-4de3-8694-bf2761270c5f.png)
I've tried restarting it like 5 times, my PC too.

**Comment by maximmax42** [comment]
Your ID works for me. The error in the bottom right is "Connection failed (wrong ID?)" I assume?
Do you have game activity enabled for your account?

**Comment by pablogonzales2009** [comment]
I do have it enabled.

**Comment by maximmax42** [comment]
Try adding the app to firewall/antivirus exception, maybe it cuts off the connection to discord.

**Comment by maximmax42** [comment]
Any updates?

**Comment by pablogonzales2009** [comment]
Sorry that I didn't respond, not that active on Github.
I added an exception, and now instead of giving me an error, it just keeps connecting.

**Comment by maximmax42** [comment]
Well that changed something. Maybe add Discord as well?

**Comment by maximmax42** [comment]
If there's any updates, please comment.
