### ISSUE TITLE
Opens only in the task manager

### ISSUE THREAD

**Issue by Ahmedelhadidey** [maximmax42/Discord-CustomRP#201]
Just installed it and tried to open it but it appears only in the task manager

**Comment by Ahmedelhadidey** [comment]
Yes, it's successful but doesn't open
The first time installing it asked and I choose no then I uninstalled and reinstall it but this time it didn't ask about allowing analytics

**Comment by maximmax42** [comment]
Hm. If you said no it should've worked.

**Comment by Ahmedelhadidey** [comment]
I left it in the task manager and eventually it opens after about thirty minutes, that's weird

**Comment by maximmax42** [comment]
That's... interesting.
