### ISSUE TITLE
Latest Version Triggers Windows Defender

### ISSUE THREAD

**Issue by TheShinyScouter** [maximmax42/Discord-CustomRP#206]
**Describe the bug**
Latest version triggered Windows Defender as a severe Trojan.

**To Reproduce**
1. Install latest version from the app's built-in updater.

**Expected behavior**
Windows Defender will trigger, marking the new file as a severe Trojan.

**Useful Info**
 - Windows Version: 10
 - Application Version: 1.17.9

**Comment by maximmax42** [comment]
Again? JFC.
Can you give me your defender's definitions version?

**Comment by RogerDMR32** [comment]
Same issue here. 
> Can you give me your defender's definitions version?
Heres all relevant version info for defender:
Windows Security Application Version: 1000.25873.0.9000
Windows Security Service Version: 1.0.2305.24001-0
Antimalware Client Version: 4.18.23050.3
Engine Version: 1.1.23050.3
Antivirus Version: 1.391.1171.0
Antispyware Version: 1.391.1171.0

**Comment by maximmax42** [comment]
> Same issue here.
> 
> > Can you give me your defender's definitions version?
> 
> Heres all relevant version info for defender: Windows Security Application Version: 1000.25873.0.9000 Windows Security Service Version: 1.0.2305.24001-0 Antimalware Client Version: 4.18.23050.3 Engine Version: 1.1.23050.3 Antivirus Version: 1.391.1171.0 Antispyware Version: 1.391.1171.0

Thanks, I'll report to Microsoft. Again. It's so annoying. I have to do that once in 3-4 releases.

**Comment by RogerDMR32** [comment]
Yup. It sounds really annoying, hope it gets fixed soon!

**Comment by TheShinyScouter** [comment]
> Again? JFC. Can you give me your defender's definitions version?

Antimalware Client Version: 4.18.23050.5
Engine Version: 1.1.23050.3
Antivirus Version: 1.391.1348.0
Antispyware Version: 1.391.1348.0

**Comment by maximmax42** [comment]
> > Again? JFC. Can you give me your defender's definitions version?
> 
> Antimalware Client Version: 4.18.23050.5 Engine Version: 1.1.23050.3 Antivirus Version: 1.391.1348.0 Antispyware Version: 1.391.1348.0

It's still detected??? MS said they can't reproduce. Update your definitions, idk.

**Comment by Lrive** [comment]
detected again for me after updating

Antimalware Client Version: 4.18.23050.5
Engine Version: 1.1.23050.3
Antivirus Version: 1.391.2728.0
Antispyware Version: 1.391.2728.0
