### ISSUE TITLE
Connection failed (is Discord running?)

### ISSUE THREAD

**Issue by W1llam** [maximmax42/Discord-CustomRP#208]
After updating it to 1.17.9, I tried to connect it to my discord and it stopped working. I deleted it and downloaded it again and it still wasn't working. It keeps saying Connection failed (is Discord running?) when I have discord open.

**Comment by maximmax42** [comment]
https://docs.customrp.xyz/faq#the-app-says-wrong-id-is-discord-running-or-connects-indefinitely-even-though-im-sure-i-did-everythi

**Comment by W1llam** [comment]
Where do I add %appdata%\CustomRP?

**Comment by maximmax42** [comment]
To your antivirus's exceptions. How - depends on what you have, so use google.
