### ISSUE TITLE
This is semi-issue, semi-suggestion

### ISSUE THREAD

**Issue by acap09** [maximmax42/Discord-CustomRP#21]
You see, I have two discords that I have logged in to. (they both are on an application) However, the application keeps linking the rich presence to the wrong Discord account. Could you at least, add a feature to choose which discord accounts will get the rich presence? Thank you.

**Comment by maximmax42** [comment]
Yeah I'm working on that, just unsure how to implement it.

**Comment by maximmax42** [comment]
Released version 1.11. Follow this after updating: https://github.com/maximmax42/Discord-CustomRP/wiki/Setting-Up#i-use-more-than-one-discord-client-what-do-i-do
