### ISSUE TITLE
Website has multiple fake phishing virus popups.

### ISSUE THREAD

**Issue by ABUCKY0** [maximmax42/Discord-CustomRP#210]
**BEFORE POSTING**
Please check https://github.com/maximmax42/Discord-CustomRP/wiki/FAQ for a possible solution. If it's not there, then carry on with creating an issue ticket.

**Describe the bug**
The website has many phishing fake notifications, adobe popups, and other malware links.

**To Reproduce**
1. Go to the website.

**Expected behavior**
The website would be free of these virus popups.

**Screenshots**
![image](https://github.com/maximmax42/Discord-CustomRP/assets/81783950/0e61b9ea-8c4a-4bf1-8783-b6603b0c6033)
![image](https://github.com/maximmax42/Discord-CustomRP/assets/81783950/c08864d0-3fe4-44b0-a922-87721131a180)
![image](https://github.com/maximmax42/Discord-CustomRP/assets/81783950/3b481ae0-531f-425c-b3b1-7c7707952791)
![image](https://github.com/maximmax42/Discord-CustomRP/assets/81783950/eced8232-b302-4d9a-a659-70479dc26ca5)

**Useful Info**
 - Windows Version: [e.g. Windows 7, Windows 10 2004]
 - Application Version: [e.g. 1.8]

**Additional context**

**Comment by maximmax42** [comment]
These are just ads.

**Comment by ABUCKY0** [comment]
Thing is, they still appear. Whatever ad service you use is serving those ads, and if they are being served they do work.

**Comment by maximmax42** [comment]
Not sure what you're trying to say by that.

**Comment by ABUCKY0** [comment]
I'm trying to say that you are responsible for the ads that appear on your website, and those ads reflect on you and this project.

**Comment by maximmax42** [comment]
If I could, I'd use a normal ad platform like AdSense. Sadly, I'm Russian. I'll see what I can do, though I doubt this ad is a virus/scam outright. Probably just gray market thing.
