### ISSUE TITLE
my CustomRP doesnt open for some reason

### ISSUE THREAD

**Issue by salvatore231** [maximmax42/Discord-CustomRP#22]
i dont know why but for some reason it doesnt open

**Comment by maximmax42** [comment]
What do you mean by "doesn't open"? Can't install? Or once it's installed you can't open the app?

**Comment by salvatore231** [comment]
i installed the app and it worked at first, then it just popped an error and now i cant open it

**Comment by maximmax42** [comment]
It might be hidden in the tray, double click on it if it is.

**Comment by salvatore231** [comment]
when i click on it it just goes away

**Comment by maximmax42** [comment]
Weird. Then kill the CustomRP.exe process in task manager and try launching again.

**Comment by salvatore231** [comment]
it closes itself it doesnt exist in task manager

**Comment by maximmax42** [comment]
It's not listed even in "Details" tab in task manager?

**Comment by salvatore231** [comment]
nope

**Comment by maximmax42** [comment]
Well I'm confused. Try restarting PC I guess?

**Comment by salvatore231** [comment]
i tried that too. I restarted my pc and i uninstalled it and installed it like 4-5 times

**Comment by maximmax42** [comment]
Then I'm honestly at a loss. Is there even an exe at %appdata%\CustomRP? Maybe your antivirus is intervening or something?

**Comment by salvatore231** [comment]
yeah yeah there is an exe and there is no antivirus  intervening or smthing

**Comment by salvatore231** [comment]
anyway thank you very much for trying helping me out i appreciate it

**Comment by maximmax42** [comment]
And when trying to open it, it just shows up for a second and closes again?
Oh okay I have an idea. Go to %localappdata%\maximmax42 and delete all folders in there that have CustomRP in the name. Maybe you tried to put something in the presence that keeps crashing the app.

**Comment by salvatore231** [comment]
oh my god it worked i cant thank you enough man i appreciate it sooo much thank you

**Comment by maximmax42** [comment]
You're welcome! But actually, can you please send me the content of what was in your config files, so I can understand what could have caused that and maybe deploy a fix?

**Comment by salvatore231** [comment]
by accident i put the text to the key part and thats how i got the error

**Comment by maximmax42** [comment]
Uh... Elaborate please? I can't reproduce the error.

**Comment by salvatore231** [comment]
i accidentally put the text for the large image to the key for the small image and when i clicked on update the error popped

**Comment by maximmax42** [comment]
Did your text have any fancy symbols, emojis and such by chance?

**Comment by salvatore231** [comment]
no no no

**Comment by maximmax42** [comment]
Then I'm confused, because I could only replicate the error by putting like a lot of special characters in the text field. But anyway, I'll try to come up with something.
