### ISSUE TITLE
cannot open CustomRP

### ISSUE THREAD

**Issue by Nezz1** [maximmax42/Discord-CustomRP#220]
I don't know why this happened, I've been looking for information from the CustomRP website and other websites but still I can't open it, for more details, you can see it in this screenshot
![image](https://github.com/maximmax42/Discord-CustomRP/assets/150152311/e9e7471a-90a1-4486-8ad1-c8baedfeee6c)
I'm using windows 7 which is a little outdated.

**Comment by maximmax42** [comment]
Try the steps from the last paragraph of the message.

**Comment by Nezz1** [comment]
I did it, and it's still

**Comment by maximmax42** [comment]
After you installed the app for the first time, did it show this error right away?

**Comment by Nezz1** [comment]
> After you installed the app for the first time, did it show this error right away?

Yes, this is the first time I installed this application

**Comment by maximmax42** [comment]
> > After you installed the app for the first time, did it show this error right away?
> 
> Yes, this is the first time I installed this application

Hm. Welp, I'm not sure then what I can do. I guess something broke support for Windows 7.

**Comment by Nezz1** [comment]
> > > After you installed the app for the first time, did it show this error right away?
> > 
> > 
> > Yes, this is the first time I installed this application
> 
> Hm. Welp, I'm not sure then what I can do. I guess something broke support for Windows 7.

Maybe some fix with the application?

**Comment by maximmax42** [comment]
[test.zip](https://github.com/maximmax42/Discord-CustomRP/files/13327724/test.zip)
Extract to `%appdata%\CustomRP`, replace all, start the app. Should fix. If not - tell me what other files it wants.

**Comment by maximmax42** [comment]
Or just install 1.17.15.

**Comment by Nezz1** [comment]
What? did you actually fix that? and this really works, thank you very much...
