### ISSUE TITLE
I have problem with my status, when i wos plaing in other game.

### ISSUE THREAD

**Issue by TT1yava4ka** [maximmax42/Discord-CustomRP#229]
Hello. When I update my status while playing another game, the discord puts the game I'm playing with in my status, not customRP. How do I make the status customized in CustomRP if I'm playing a different game?
![Скриншот 12-02-2024 133220](https://github.com/maximmax42/Discord-CustomRP/assets/159772625/c7f7c7ca-8c10-435b-86e3-cbef1ab03d70)

**Comment by maximmax42** [comment]
![image](https://github.com/maximmax42/Discord-CustomRP/assets/2225711/ff5e5a53-ba3c-49d8-9a7e-add85b815238)
You can only disable the other game's presence.
