### ISSUE TITLE
make an uninstall executable

### ISSUE THREAD

**Issue by Codder13** [maximmax42/Discord-CustomRP#23]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maximmax42** [comment]
It's most definitely uninstallable. If you can't find the uninstall link in the start menu, on Win10 you can right click on the launch link and press uninstall, on Win7 you can go to "Programs and features" I think.

**Comment by maximmax42** [comment]
Well unless you downloaded zip, then you can just quit and delete the folder.

**Comment by Codder13** [comment]
thx
