### ISSUE TITLE
Discord Link is Expired

### ISSUE THREAD

**Issue by manasloth** [maximmax42/Discord-CustomRP#230]
Please update the discord link!

**Comment by maximmax42** [comment]
It's not expired. You're probably banned. What's your username?

**Comment by manasloth** [comment]
I'm not banned as I'm talking to you right now, haha.

The issue isn't the link, I guess it's the way right click -> copy link
takes the discord link and invalidates it. Clicking on it then copy pasting
it worked. So this is an invalid issue.

**Comment by maximmax42** [comment]
Interesting.
