### ISSUE TITLE
Buttons don't work anymore

### ISSUE THREAD

**Issue by Nic0d3mu5** [maximmax42/Discord-CustomRP#233]
Hi, I think last time I used my buttons was like 2 days ago, and it worked, but today I click on it and nothing happens.

**Comment by maximmax42** [comment]
Discord is having a moment™, not something I can fix. At least as far as I know.

**Comment by Nic0d3mu5** [comment]
Starts to be a long moment™ : /
But if you can't do anything, let's just hope for the best. ^^

**Comment by maximmax42** [comment]
The only buttons that seem to work are the "join/spectate game" and streaming's "watch". So, non-custom ones.

**Comment by Nic0d3mu5** [comment]
Ok, and it seems to be temporary?

**Comment by maximmax42** [comment]
Honestly no idea. Could be either, to be honest.

**Comment by Nic0d3mu5** [comment]
Ok... Fingers crossed then.

**Comment by Brugman** [comment]
Has anyone gotten custom buttons working since? I think Discord ripped them out.

**Comment by Nic0d3mu5** [comment]
It works for me now yes.

**Comment by maximmax42** [comment]
They've fixed that like 2 months ago.

**Comment by maximmax42** [comment]
@Brugman Check CustomRP window. Does it say "Updating presence" in the bottom? If yes, check the image URLs, they might be too long or somehow corrupted.
One person did recently say that buttons didn't work for them and that was the cause. If the app is stuck on updating, it doesn't actually send the presence, only you see it, and apparently buttons don't work in that state.

**Comment by Brugman** [comment]
Apologies, it's just not showing on my primary device. I can see them from my phone.
