### ISSUE TITLE
No image in status

### ISSUE THREAD

**Issue by 74blades** [maximmax42/Discord-CustomRP#234]
![image](https://github.com/maximmax42/Discord-CustomRP/assets/161824300/151fa489-48f0-4b80-9862-0b8701cd69d2)
I uploaded my image wherever possible on the discord developer page, but it is not showing in the status

**Comment by maximmax42** [comment]
It can take a while for an image to appear. Discord is slow sometimes. You can either wait (and reconnect every now and then) or upload the image somewhere else and use a direct url.
