### ISSUE TITLE
i cant click the "update  presense"

### ISSUE THREAD

**Issue by issam-pro** [maximmax42/Discord-CustomRP#238]
i did evry thing correct but i cant click that and when i click connect it dosent work...

**Comment by maximmax42** [comment]
"Update presence" is disabled until CustomRP connects to Discord.
> i click connect it dosent work...
Can you be more specific please?

**Comment by dadodasyra** [comment]
Same issue, it's sutck on Connecting

**Comment by maximmax42** [comment]
> Same issue, it's sutck on Connecting

https://docs.customrp.xyz/faq#the-app-says-wrong-id-is-discord-running-or-connects-indefinitely-even-though-im-sure-i-did-everythi
If nothing mentioned helps - I can't help.

**Comment by dadodasyra** [comment]
Figure out I had another discord running in background without account
