### ISSUE TITLE
Id is wrong and wont connect 

### ISSUE THREAD

**Issue by ProdigalVoid** [maximmax42/Discord-CustomRP#24]
![Capture](https://user-images.githubusercontent.com/65845420/129098586-b8475188-0543-41de-9be7-ea40c64fe264.PNG)
and says connection failed maybe discord running

**Comment by maximmax42** [comment]
Just to check, you are running a desktop discord client, and not in browser, right? Try adding CustomRP and Discord in antivirus/firewall exceptions. If doesn't work, I have no clue how to solve it, sadly.

**Comment by MasterCubo** [comment]
> ![Capture](https://user-images.githubusercontent.com/65845420/129098586-b8475188-0543-41de-9be7-ea40c64fe264.PNG)
> and says connection failed maybe discord running

check the issue number #19 and see what I said. It worked after that mysteriously.

**Comment by maximmax42** [comment]
> Just to check, you are running a desktop discord client, and not in browser, right? Try adding CustomRP and Discord in antivirus/firewall exceptions. If doesn't work, I have no clue how to solve it, sadly.

Well I already suggested the same thing. I can only add that you probably need to restart both discord and the app (or pc as a whole) for it to take effect.

**Comment by maximmax42** [comment]
If the issue hasn't been solved, please comment again.

**Comment by tomasmendes01** [comment]
I had the same issue because I was launching Discord as administrator.
