### ISSUE TITLE
Just installed this, uploaded an image and trying to use it. Its not showing the custom image, I read the faq but theres nothing about it. 

### ISSUE THREAD

**Issue by alexandremix** [maximmax42/Discord-CustomRP#241]
Install app, follow all procedures, create an image 1024*1024 upload to asset, image appears on the app list, if you use the image it does not appear on the rich presence. 

There's nothing on FAQ about this. 

I just installed this and did everything correctly the only issue is the images not working at all.

**Comment by maximmax42** [comment]
Discord sometimes doesn't make the image available right away, just wait.
I'll add it to FAQ later.
