### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by TheSrBig** [maximmax42/Discord-CustomRP#242]
https://www.virustotal.com/gui/file/99a13b46fc5ec89169132f3ec365c77eabcb31ea07efab203c7795da948b1774

**Comment by maximmax42** [comment]
2/72 is not a virus.
One of those detections is just "low score", and the other is detected with AI.
Anyway, no, there are no viruses in the app. Source code is available for everyone to inspect, binary build process is also open. Can't sneak anything in without people noticing.
