### ISSUE TITLE
Dropdown doesn't fit on screen

### ISSUE THREAD

**Issue by IS4C4SI** [maximmax42/Discord-CustomRP#249]
**Problem**
There are a lot of images in my activity and when I open the dropdown list, 1/3 of them are hidden behind the screen space

**Decision**
Define the maximum length of the dropdown list like this:
1. Adaptive: Maximum vertical value, for example: 1080px / 2 = 540px
2. Simple: Set a constant length for a dropdown list = 275px - this is half the program window on a screen with a resolution of 1920x1080

**Comment by maximmax42** [comment]
Huh. I thought WinForms accounts for that automatically. Was there no arrow on the bottom of the list?

**Comment by IS4C4SI** [comment]
Yes but no, in the window element itself yes,<details><summary>Details</summary><img src="https://i.postimg.cc/7h7VYw1n/image.png"><a href="https://i.postimg.cc/7h7VYw1n/image.png" target="_blank">image.png</a></details>but in the interface element no.<details><summary>Details</summary><img src="https://i.postimg.cc/MHj6rr7L/video.gif"><a href="https://i.postimg.cc/MHj6rr7L/video.gif" target="_blank">video.gif</a></details>

**Comment by maximmax42** [comment]
Okay, so. How many images do you have uploaded? Because apparently the combobox only allows for 100 entries max.
(Оффтоп, но нафига загружать так много изображений?????)

**Comment by maximmax42** [comment]
Though it looks like it still goes offscreen even if there's 100 elements.

**Comment by maximmax42** [comment]
*Oh.* I'm dumb. 100 is the number of elements shown *at once*. I'll set it to 30, should fit on any screen.

**Comment by IS4C4SI** [comment]
Спасибо за внимание, в моей активности больше 150 изображений, я рад что вы исправили проблему и с нетерпением буду ждать новой версии.
