### ISSUE TITLE
New discord activity update ruined custom timestamps

### ISSUE THREAD

**Issue by hitoridoga** [maximmax42/Discord-CustomRP#254]
New update that released as of 24/08/14 (for me, not out for me on my second account) has ruined the custom timestamp in CustomRP and now only shows a timestamp based on the last presence update no matter what. 

**Screenshots**
![image](https://github.com/user-attachments/assets/15cbfb49-c985-47c6-92f5-47d5be922150)

**Comment by maximmax42** [comment]
F
I probably can't do shit about that, but I'll check once I'm home.

**Comment by maximmax42** [comment]
![image](https://github.com/user-attachments/assets/a2c7bd79-9947-445b-bab9-cf035853caf6)
I got that update too. Looks like they fixed it.

**Comment by maximmax42** [comment]
Except they got rid of "remaining", apparently.

**Comment by maximmax42** [comment]
...And now the timer does show more than 24 hours. Crap. I'll have to fix the local time feature.
