### ISSUE TITLE
Timestamps count past 24h

### ISSUE THREAD

**Issue by Larsundso** [maximmax42/Discord-CustomRP#256]
**Describe the bug**

**To Reproduce**
1. Set "Your local time" as timestamp
2. Activate the presence
3. Wait until tomorrow
4. Observe your Discord activity

**Expected behavior**
The Timestamp should show your local time

**Actual behavior**
The Timestamp now counts past 24h

**Useful Info**
 - Windows Version: Windows 11
 - Application Version: 1.17.27 

**Additional context**
Discord recently updated their Activity display.
Before this update, a timestamp going past 23:59:59 would reset to 0:00:00
Now, it just continues counting up.
A possible solution would be to periodically set the timestamp to "Today at 0:00:00" when passing the 23:59:59 mark

**Comment by maximmax42** [comment]
Should be fixed in 1.17.28.

**Comment by BoYanZh** [comment]
I can reproduce it in 1.17.28.

**Comment by maximmax42** [comment]
> I can reproduce it in 1.17.28.

With local time timestamp?

**Comment by BoYanZh** [comment]
> > I can reproduce it in 1.17.28.
> 
> With local time timestamp?

Yes.

**Comment by maximmax42** [comment]
h

**Comment by maximmax42** [comment]
h

**Comment by maximmax42** [comment]
https://ci.appveyor.com/api/buildjobs/5qfx6pmyflhxplqc/artifacts/CustomRPC%2FBuild%2FArtifacts%2FCustomRP%201.17.28.exe
Please test this version. I added a 5 second buffer, so basically it should update at 00:00:05.

**Comment by BoYanZh** [comment]
Got it, testing now.

**Comment by BoYanZh** [comment]
It still stops working on the 2nd night. The first night was good, but now the time is 27:38:16.

**Comment by maximmax42** [comment]
Huh... So it only works once? That's weird.

**Comment by maximmax42** [comment]
Closing this since no one else said they have this issue.
