### ISSUE TITLE
Endless inscription "updating presence..."

### ISSUE THREAD

**Issue by MassiRo** [maximmax42/Discord-CustomRP#257]
**Describe the bug**
Endless inscription "updating presence..." and  ts visible, but locally for me. Others don't see it idc why. 

**To Reproduce**
1. Entering all necessary data
2. Click on connect button
3. Endless inscription "updating presence..."

**Expected behavior**
The status should be visible not only locally for me

**Screenshots**
https://youtu.be/QVi2dEAXfew

**Useful Info**
 - Windows Version: Windows 10 
 - Application Version: 1.17.27

**Additional context**
I tried to change id to another application and its still happens. Tried other versions, but still doesnt work. This appeared after the last discord update

**Comment by maximmax42** [comment]
You're using images hosted on Discord. Their links get too long too quick. Upload your images somewhere else or use a URL shortener.
