### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by 6oody** [maximmax42/Discord-CustomRP#26]
when i install it it just doesn't exsit even in my task manger 
btw it was working from like 5 days or smth like that and i tried to delete it and downlaod it again and it still doesn't work or even appear idk why

**Comment by 6oody** [comment]
okai i just saw this issue and it was like my issue and i just fixed it thanks for u @maximmax42 
https://github.com/maximmax42/Discord-CustomRP/issues/22#issuecomment-893539855

**Comment by maximmax42** [comment]
I'll add this solution to FAQ as well.
