### ISSUE TITLE
Last Discord update broke it again

### ISSUE THREAD

**Issue by Nic0d3mu5** [maximmax42/Discord-CustomRP#260]
CustomRP can't connect to Discord since the last update. Only saying "Connecting...".

**Comment by maximmax42** [comment]
https://docs.customrp.xyz/faq#the-app-says-wrong-id-is-discord-running-or-connects-indefinitely-even-though-im-sure-i-did-everythi

**Comment by Nic0d3mu5** [comment]
Indeed, my bad... Shame on me to not even have reboot my PC... Sorry.
