### ISSUE TITLE
Image/Key connected but all I can see is a "?" Symbol

### ISSUE THREAD

**Issue by LostSkyZ** [maximmax42/Discord-CustomRP#262]
**BEFORE POSTING**
Please check https://github.com/maximmax42/Discord-CustomRP/wiki/FAQ for a possible solution. If it's not there, then carry on with creating an issue ticket.

**Describe the bug**

I have taken the URL of gifs from Tenor and Imgur to use on my discord rich presence, I don't get any errors saying the key is too long so I thought it would be working fine but it instead just comes up with the blank question mark when I go to activity status

**To Reproduce**

**Expected behavior**
The media gif to appear normally on status

**Screenshots**
![image](https://github.com/user-attachments/assets/fad65a66-bc8c-43be-b8b7-5854d0872d2a)
![image](https://github.com/user-attachments/assets/54672130-112e-4c54-b64e-a2af76c1685d)

**Useful Info**
 Windows 11
Version 1.18.1

**Additional context**

**Comment by maximmax42** [comment]
The link you used is not a direct link to the image. It's a link to a web page. You can get a direct link by right clicking the image and pressing "Copy image URL" or similar.

**Comment by LostSkyZ** [comment]
Thank you, it ended up solving the issue
