### ISSUE TITLE
Buttons Not working

### ISSUE THREAD

**Issue by Balajinitin** [maximmax42/Discord-CustomRP#264]
Button is not working. I am not able to able to add button. i tried with different websites, youtube video links etc but nothing works. not even button 1 and 2

**Useful Info**
 - Windows Version: Windows 11 Home (Dell)
 - Application Version: latest (checked for upfates too)

**Comment by maximmax42** [comment]
See #248.

**Comment by Balajinitin** [comment]
i cannot see buttons on mobile too

**Comment by maximmax42** [comment]
Well, they might've broken it on mobile too. Other people will definitely see them.

**Comment by Balajinitin** [comment]
Yup. its broken on mobile too. but other people are able to see it. (confirmed it via alt acc.) thnx and sorry for trouble
