### ISSUE TITLE
Pipes

### ISSUE THREAD

**Issue by NotLiso** [maximmax42/Discord-CustomRP#28]
**BEFORE POSTING**
Please check https://github.com/maximmax42/Discord-CustomRP/wiki/FAQ for a possible solution. If it's not there, then carry on with creating an issue ticket.

**Describe the bug**
randomly showing pipes

**To Reproduce**
idk i just got the app run in tray and it gives me that, more pipes = lag

**Expected behavior**
to work normally

**Screenshots**
https://kamerzysta.is-in-my-basement.xyz/lisosus/06183txv its a upload.systems pic

**Useful Info**
 - Windows Version: Win 10
 - Application Version: 1.11.3

**Additional context**

**Comment by maximmax42** [comment]
That's... weird. It's only supposed to open if you press Ctrl+Connect button. I'll look into it.

**Comment by maximmax42** [comment]
Should be fixed with 1.11.4.
