### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by NotLiso** [maximmax42/Discord-CustomRP#29]
what are the Pipe window for?

**Comment by maximmax42** [comment]
It's for when you have more than 1 Discord client running at the same time. If you wanna change what account will the presence show up in, you would change the number, typically to 1.

**Comment by maximmax42** [comment]
Btw if the issue is closed you can still comment. Unless you can't, then plz tell me about it.

**Comment by NotLiso** [comment]
ahaa ok
