### ISSUE TITLE
Custom Timestamps

### ISSUE THREAD

**Issue by ItsMrCube** [maximmax42/Discord-CustomRP#3]
### Custom Timestamps

I noticed that currently the only timestamps options are "Since CustomRP started" or "Your local time".
It would be great to have the ability to enter a custom timestamp, this would be useful to make, for example, custom countdowns.
Formats like epoch or just a time and date selector would be a nice touch.

Thanks.

**Comment by maximmax42** [comment]
Oh right I completely forgot I wanted to add that! I'll work on it the next few days.

**Comment by maximmax42** [comment]
Spent a couple of days trying different implementations but stopped at the basic one with just one date and time picker. Doesn't look that pretty but it's working well enough. Hopefully.
You can download update at https://github.com/maximmax42/Discord-CustomRP/releases/tag/1.8.1 or wait till the app will ask for update itself.

**Comment by ItsMrCube** [comment]
I tried updating the app and downloading the portable version but 1.8.1 seems to be crashing instantaneously on start...

Should I open a new issue or are you aware of this?

**Comment by maximmax42** [comment]
Huh. That's weird, I'll investigate once I'm on PC.

вт, 10 нояб. 2020 г., 11:49 MrCube <notifications@github.com>:

**Comment by maximmax42** [comment]
Should be fixed by now. But reopen if anything is wrong again.
