### ISSUE TITLE
Timer Issues

### ISSUE THREAD

**Issue by TheRichDarth** [maximmax42/Discord-CustomRP#4]
**Description:**
When using the 'custom timestamp' feature, the timer is WAY off

**To Reproduce:**
1. Choose 'custom timestamp' for timestamp 
2. Set to a date a few days in the future
     I am writing this on 12-30-2020, 9:02 PM
     The Custom time is set to 1/3/2020, 6:00 AM
     The timer reads 15:03 
     Obviously, this clock is far from what it should be.

I don't know if the issue is caused by the new year or what. Also, changing the date didn't seem to have any effect, only the time. I would change the day from 1/1 or 1/3 or 1/27 and the time would not change. Is this behavior intended? It seems non-intuitive.

**Comment by maximmax42** [comment]
Hello, unfortunately, it's a Discord limitation, it can only display hours in the presence and ignores days, or to be more precise, if there's more than 24 hours, when time in presence reaches 23:59:59, it loops back to 00:00 and vice versa. It's described in a tooltip shown when you hover over the "Timestamp" text, but I don't blame you if you didn't even know you can do that, I should make it more obvious in the app.

Being able to choose any time and date is confusing, I know, but I can't think of anything else that wouldn't be less confusing. I was thinking of a field to just input hours, minutes, seconds and a switch whether the time you chose was in past or in future (or whether you wanted to count from that time or to that time), but it would probably be more confusing that this one.

**Comment by TheRichDarth** [comment]
Thank you for the clarification. This is a really cool piece of software
and I’m glad I was able to get it working. Thanks.

**Comment by maximmax42** [comment]
No problem, and thank you as well! Happy New Year!

**Comment by dvdcd** [comment]
Making this more obvious in app and/or adding this to the FAQ would be awesome!

**Comment by maximmax42** [comment]
Yeah I'll add this to FAQ.
