### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by leopoldhub** [maximmax42/Discord-CustomRP#43]
Add a linux version for most used distributions like debian based ones

**Comment by maximmax42** [comment]
Sadly impossible because the app is written in a Windows only library.

**Comment by gitdrug** [comment]
wine  also works so just use wine

**Comment by meisme-dev** [comment]
it doesnt work on wine

**Comment by maximmax42** [comment]
I think you need to install .NET dependencies before using it. I dunno, I haven't tried.

**Comment by meisme-dev** [comment]
it runs on wine but discord doesnt detect it
