### ISSUE TITLE
Timestamp Bug

### ISSUE THREAD

**Issue by QuantumV2** [maximmax42/Discord-CustomRP#47]
When i click to custom timestamp in Timestamps section and place time in the past (like 2020 etc) it just show time that Custom RP was running, im pretty sure it's a bug, but how can i fix it? 
![image](https://user-images.githubusercontent.com/83087109/131712073-6cda8181-5de8-4062-9daa-83552c461597.png)
![image](https://user-images.githubusercontent.com/83087109/131712171-a94283c8-58e8-4365-a16f-d9693fcfa359.png)

**Comment by QuantumV2** [comment]
version 1.11.6

**Comment by maximmax42** [comment]
This actually isn't a bug. Discord can only show 24 hours max, or rather 23:59:59, and then it loops back to 0:00. I didn't know how else to implement that interface.

**Comment by maximmax42** [comment]
So basically, only thing that matters is the time, and whether or not the overall date is in the past or the future at the time of pressing the update presence button.
