### ISSUE TITLE
rich presence buttons

### ISSUE THREAD

**Issue by vilchu** [maximmax42/Discord-CustomRP#5]
Hello! Is there possibility to add rich presence buttons like in picture below?

![image](https://user-images.githubusercontent.com/55512609/105630922-5fa75e00-5e54-11eb-9ffc-6c77efc16c0b.png)

Thanks!
-Vilchu

**Comment by maximmax42** [comment]
Wait, is that a mockup image or someone's real profile? If real, are these buttons working?

**Comment by vilchu** [comment]
It's someone's real rich presence, and when you click the buttons it'll take you to the link, so I thought it would be cool if your app could somehow do the same, won't force you tho, but would be cool

**Comment by maximmax42** [comment]
o.o
I honestly have no idea how it's done, it's nowhere in the specification of the presence. Can you, by any chance, ask the person how they did that?

**Comment by vilchu** [comment]
I'm no coder but here's JS other guy made
https://github.com/Mega-Mewthree/BetterDiscordPlugins/blob/master/Plugins/AutoStartRichPresence/AutoStartRichPresence.plugin.js

Hope this helps owo

**Comment by maximmax42** [comment]
Huh... Apparently it's a recent addition, not fully implemented yet, as there is no official documentation. The library I'm using for presence doesn't support custom buttons yet, but the author says [they will implement it eventually](https://github.com/Lachee/discord-rpc-csharp/issues/112). Library used in BD plugin does support it, but sadly, it's in a different language.
So, for now there's nothing I can do, but I will definitely implement these once the library support will be added.

**Comment by vilchu** [comment]
Oohh.. I see, thank you and It's ok!

**Comment by vilchu** [comment]
Sorry, not related to buttons anymore, but is there way to add more easily the "profiles", like with Strukteon's app below
![image](https://user-images.githubusercontent.com/55512609/105635666-c173c200-5e6c-11eb-9e69-be66edb01642.png)

But since Strukteon said they will not be updating their app anymore, I'm happy that I found your app. 
I know, there's the save and load presets, but It saves the last edit I've done and doesnt "update" if I've updated the preset. owo

**Comment by maximmax42** [comment]
Yeah, I also wanna add that, but so far I'm not sure how to store the profiles. So once I figure out, I'll add that too.

**Comment by vilchu** [comment]
Thank you so very much! and sorry for taking your time 😅

**Comment by maximmax42** [comment]
And now the buttons are implemented in the 1.9 release!
