### ISSUE TITLE
Connect but nothing appeared on Discord

### ISSUE THREAD

**Issue by DTJMdr** [maximmax42/Discord-CustomRP#56]
Hi, I'v a bug with your software, when I open it and connect It for Discord, the Rich Presence is not working.
I already restart the software, Discord and my computer.
I change the ID to a new app to Discord Dev but not still working.
And i already delete the data in the "D:\Users\MELOL\AppData\Local\maximmax42" but not still working
I even uninstall and install the last version of the software on "www.customrp.xyz" 
I try everything but there not still working :/

If someone can help me for this problem pls

**Comment by maximmax42** [comment]
It connects successfully, but doesn't show anything? Or does it not connect at all?

**Comment by DTJMdr** [comment]
It connects successfully but doesn't show anything on Discord.
The software doesn't show me any error.

**Comment by DTJMdr** [comment]
And i'v deactivate my Firewall and my Antivirus software

**Comment by maximmax42** [comment]
In Discord settings: `Activity Status` -> check `Display current activity as a status message.`

**Comment by DTJMdr** [comment]
> In Discord settings: `Activity Status` -> check `Display current activity as a status message.`

Yes, i active

**Comment by maximmax42** [comment]
Do you have more than one discord client running on the same PC?

**Comment by DTJMdr** [comment]
Nope, that the Only

**Comment by DTJMdr** [comment]
If you want i will give you a new about that I 1 day.

**Comment by maximmax42** [comment]
Huh. Very weird. I'm not even sure why it's not working.
But just in case, try to run this:
[Debugger.zip](https://github.com/maximmax42/Discord-CustomRP/files/7148472/Debugger.zip)
It should only show one pipe active with your username.

**Comment by DTJMdr** [comment]
> Huh. Very weird. I'm not even sure why it's not working.
> But just in case, try to run this:
> [Debugger.zip](https://github.com/maximmax42/Discord-CustomRP/files/7148472/Debugger.zip)
> It should only show one pipe active with your username.

![Capture d’écran (119)](https://user-images.githubusercontent.com/90529096/132960873-7bf8cfa7-6e19-41c2-9f18-e3644dc0a398.png)

**Comment by maximmax42** [comment]
I'm at a loss then. Are you sure it's not showing up at all?

**Comment by DTJMdr** [comment]
Nope, I will give you new next day men.

**Comment by maximmax42** [comment]
Alright then.

**Comment by maximmax42** [comment]
Anything new?

**Comment by DTJMdr** [comment]
> Anything new?

Oh sorry, well he work now, I don't now how 🤔, but it's work.

**Comment by maximmax42** [comment]
Weird. Well I'll close the issue then. But if you have anything else to say feel free to reopen.
