### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by HeresJohnny320** [maximmax42/Discord-CustomRP#57]
so when i hit connect its stuck on connecting 
![image](https://user-images.githubusercontent.com/34362911/133417027-abeb771b-a40a-409d-a4c4-60dbc5ec68aa.png)
then when i go back to an older version its some how broke too so idk if the new update broke it or if its just me but i did had it working before the update

**Comment by maximmax42** [comment]
It might be just a timeout from Discord. Wait like 10-20 minutes. If still nothing, try adding the app to antivirus/firewall exceptions and restart pc.

**Comment by HeresJohnny320** [comment]
yep that seem to fix it 
it was just a timeout issue from discord
