### ISSUE TITLE
The application stopped running

### ISSUE THREAD

**Issue by good-repo** [maximmax42/Discord-CustomRP#58]
At first everything worked for me
But now I'm trying to launch CustomRP and nothing comes out, there is not even a tray icon.
I checked that the antivirus does not have a block for this application

It just doesn't start and I can't figure out what's the matter.

**Comment by maximmax42** [comment]
Press Win+R, type `%localappdata%\maximmax42` and delete or rename folders with CustomRP in the name, then start the app.

**Comment by good-repo** [comment]
Yes it works now
Thx
