### ISSUE TITLE
Italian translation.

### ISSUE THREAD

**Issue by DJD320** [maximmax42/Discord-CustomRP#6]
I can help with the Italian translation, if you need it.

**Comment by maximmax42** [comment]
Great! How would you prefer to get localization strings? Just a txt file?

**Comment by DJD320** [comment]
Okay! I don't know if you prefer other methods, you tell me.

**Comment by maximmax42** [comment]
[strings.xlsx](https://github.com/maximmax42/Discord-CustomRP/files/5868419/strings.xlsx)
Hope that works for you.

**Comment by DJD320** [comment]
Ok. Imma start working rn!

**Comment by maximmax42** [comment]
Oh almost forgot, how would you like to be credited? As DJD320 or smth else? Any link to promote, like YT channel or some other social page?

**Comment by DJD320** [comment]
Crediting me as DJD320 is more than fine, thank you.
Here is the file with everything translated into Italian.
[strings.xlsx](https://github.com/maximmax42/Discord-CustomRP/files/5868632/strings.xlsx)

**Comment by maximmax42** [comment]
Alright, thank you! Any way I can contact you when I'm gonna need more translations?

**Comment by DJD320** [comment]
Contact me on discord: `DJD320#7656`

**Comment by maximmax42** [comment]
Aight, thank you!
