### ISSUE TITLE
doesnt launch after updating from 1.11.10

### ISSUE THREAD

**Issue by lolpowerluke** [maximmax42/Discord-CustomRP#69]
**Describe the bug**
doesnt launch

**To Reproduce**
update (gives this error)
![image](https://user-images.githubusercontent.com/47672899/143037781-b0eb3495-bf3a-460e-9a6b-0642b65446e8.png)
when opening the exe file (the one that appeared on the homescreen)
![image](https://user-images.githubusercontent.com/47672899/143037886-ce4b50c8-83c2-46aa-84cd-8d56db59aa2b.png)

**Expected behavior**
opens the application

**Useful Info**
 - Windows Version: 10
 - Application Version: any over 1.11.10

**Comment by maximmax42** [comment]
Seems like your antivirus is blocking it. Try adding `%appdata%\CustomRP` to exceptions.

**Comment by lolpowerluke** [comment]
also gives this sometimes
![image](https://user-images.githubusercontent.com/47672899/143117012-a7e235b2-3788-41b5-bf3d-7a18f04d85e2.png)

**Comment by maximmax42** [comment]
Yeah, definitely your antivirus is blocking it.

**Comment by lolpowerluke** [comment]
but I'll try the antivirus and see if that works

**Comment by lolpowerluke** [comment]
which file do I have to select?
cause I cant select the whole folder

**Comment by lolpowerluke** [comment]
also, do I have to reinstall the app after that?
cause I tried adding the exe file to exeptions, but it still gives that red window

**Comment by maximmax42** [comment]
If you can't select whole folder, just the .exe should work. A reinstall might not be needed, maybe the .exe got quarantined, check your antivirus.

**Comment by lolpowerluke** [comment]
could it be this?
![image](https://user-images.githubusercontent.com/47672899/143130087-8760ed45-a242-49ec-8354-54f5820d211a.png)

**Comment by maximmax42** [comment]
Looks like that was an installer file. So I guess it didn't install properly. Yeah, try reinstalling.

**Comment by maximmax42** [comment]
Don't even need to uninstall first, I think.

**Comment by lolpowerluke** [comment]
do I have to repair that file or not?

**Comment by maximmax42** [comment]
Yeah, and you can preemptively add a similar file for

**Comment by lolpowerluke** [comment]
where do I have to put this file then?
cause it asks where to put it

**Comment by maximmax42** [comment]
`%temp%` I guess?

**Comment by lolpowerluke** [comment]
works again, ty
