### ISSUE TITLE
Connection Failed(Is Discord Running?)

### ISSUE THREAD

**Issue by alastairtechnologies** [maximmax42/Discord-CustomRP#7]
Hi, I have just installed this tool, and I have created an application in the Dev Portal. After entering the **Client ID** into the app, and pressing connect, it ticks for a minute, then says `Connection Failed(Is Discord Running?)`. I have triple-checked it, and I can't seem to see what is wrong. Any help is greatly appreciated.

**Comment by maximmax42** [comment]
Hello!
Are you using a desktop Discord client or a web one?

**Comment by alastairtechnologies** [comment]
I am using the Desktop application, and I have tried disabling Cloudflare Warp too to no avail, just in case that was it.

**Comment by maximmax42** [comment]
Can you give me your application's ID so I can test it on my client?

**Comment by alastairtechnologies** [comment]
**Client ID:** `803752434710085634`

**Comment by maximmax42** [comment]
Hm... Connects for me no problems. Can you try connecting again, maybe it was Discord's caching not updating quick enough?

**Comment by alastairtechnologies** [comment]
Still not working:
![image](https://user-images.githubusercontent.com/37487746/105916648-171faa00-5fe6-11eb-8e00-ecacba5fb355.png)

**Comment by maximmax42** [comment]
Weird. Can you try restarting Discord itself?

**Comment by alastairtechnologies** [comment]
Still the same things happening.

**Comment by maximmax42** [comment]
You can, definitely. Well okay, try this id: 463054495157452801. If not, I'm kind of out of ideas.

**Comment by alastairtechnologies** [comment]
I think it isn't the ID that there is a problem with, but the connection between the app and Discord itself. Are there any apps that could interfere with said connection?

**Comment by maximmax42** [comment]
I don't think so, really. It's a local connection between two applications. Well, if you have a firewall or antivirus, you can try temporarily disabling them.

**Comment by alastairtechnologies** [comment]
Disabled Antivirus, and it is still not working. Are there any special settings in Discord itself I need maybe?

**Comment by maximmax42** [comment]
Hold on. It might, actually!
Gaming Settings -> Game Activity -> Display currently running game as a status message.
Is that enabled?

**Comment by alastairtechnologies** [comment]
Welp, I guess I have to bodge my own solution then. But thank you for the help!

**Comment by maximmax42** [comment]
Welp, sad. If you're gonna try other similar apps, can you tell me whether they're working or not? I just wanna know if it's an issue with my app or something with your pc.

**Comment by alastairtechnologies** [comment]
Ya, bossmang.

**Comment by maximmax42** [comment]
Not sure what that means.

**Comment by alastairtechnologies** [comment]
Yes, bossman.

**Comment by maximmax42** [comment]
Sorry I'm being dumb, you meant "Yes, other solution by that name is working" or "Yes, I'll tell you if it's gonna work"?

**Comment by alastairtechnologies** [comment]
"Yes, I'll tell you if it's gonna work." Sorry about that, just quoting the Expanse. Anyway, I think I found out what my problem is. A couple of months ago I had problems with Discord trying to update itself and continuously failing. I fixed it by setting Discord to always run as Administrator, which it seems interferes with the connection your app attempts to make with the Discord client. I have been trying to fix it, but so far nothing has worked. I have submitted a support ticket, so we'll see where it goes. I'll keep you posted if anything changes.

**Comment by alastairtechnologies** [comment]
Hey @maximmax42, I finally got my client working again. It seems there is a problem with the current release of Discord, which was fixed with the PTB pre-release. Don't know how helpful that is, but whatever. By the way, is there any way to change the type of application it is displayed as? I have noticed that Spotify shows as listening to, rather than playing. If it isn't, then it is fine.

**Comment by maximmax42** [comment]
Oh I had a problem with client updating as well, like a month ago. I basically fixed it by manually downloading an update package, extracting it, and editing some files. A complete reinstall would also probably work but I didn't wanna lose emoji history xd
And sadly, no, only bots can change their activity type.

**Comment by alastairtechnologies** [comment]
So how does Spotify's RPC work then? Is it because they are big, they get better features?

**Comment by maximmax42** [comment]
Well, yeah, pretty much.

**Comment by callmenikk** [comment]
I had same issue here, restarting of discord helped the problem

**Comment by WalterWitch** [comment]
can u tell me how to solve that issue i have same issue connection failed(is discord running ?)

**Comment by maximmax42** [comment]
> can u tell me how to solve that issue i have same issue connection failed(is discord running ?)

https://docs.customrp.xyz/faq#the-app-says-wrong-id-is-discord-running-or-connects-indefinitely-even-though-im-sure-i-did-everythi

**Comment by breakdownhxc** [comment]
> 

so i just ran into this issue and was able to fix it. if you right click on the program and run as administrator it didn't work for me. what i had to do was go into the properties and change the compatibility to run as administrator and that fixed it for me.

**Comment by GoobsieWoobsie** [comment]
Getting this issue in 2025 July 6th. Only fix is uninstalling and re-installing custom rp.
