### ISSUE TITLE
Buttons aren't working

### ISSUE THREAD

**Issue by ItsMrCube** [maximmax42/Discord-CustomRP#8]
**Describe the bug**
The buttons show up but they don't link anywhere when clicked.

**To Reproduce**
1. Set a button with a link (in my case it's `https://mrcube.live`)
2. Click the button on Discord

**Expected behavior**
The website should open in your browser

**Useful Info**
 - Windows Version: Winddows 10
 - Application Version: 1.9
 - Browser: Firefox DEV

**Comment by maximmax42** [comment]
Yeah I have the same thing, but other people say buttons in my profile work. I tested that with another library (discord-rpc for node.js) and it still had the same behavior. So I don't think it's my app's issue, it might be Discord being weird.

**Comment by ItsMrCube** [comment]
After researching the origin of this, I found out that it only works if you view the profile from a web browser (Firefox in my case).

**Comment by maximmax42** [comment]
Wow, interestingly enough, I don't even see the status in browser.

**Comment by maximmax42** [comment]
Can confirm at least one person can use a button in my profile from a standalone client.

**Comment by vilchu** [comment]
Hello, just commenting
Yes, It's known that you yourself can't click the buttons, but everyone else can though click them, It's same with BetterDiscords case.
Idk if it's on purpose or just bug, but it's known.

**Comment by binarynoise** [comment]
Would you temporarily disable the buttons until Discord fixes that?

**Comment by maximmax42** [comment]
Why? They do work overall, it's just you yourself that can't click on them.

**Comment by binarynoise** [comment]
Ah, ok, then I misunderstood the issue. I'm sorry
