### ISSUE TITLE
It won't open, like at all, not even the task manager.

### ISSUE THREAD

**Issue by Noxxe-0001** [maximmax42/Discord-CustomRP#80]
**BEFORE POSTING**
Please check https://github.com/maximmax42/Discord-CustomRP/wiki/FAQ for a possible solution. If it's not there, then carry on with creating an issue ticket.

**Describe the bug**
The application does not open at all when I try to click on the shortcut that is in the Start menu and also when I added the shortcut to my taskbar, and it isn't even showing in my taskmgr either.

**To Reproduce**
1. Install and click the shortcut in the start menu.
2. Nothing happens.

**Expected behavior**
The program should run when I click the shortcut.

**Screenshots**

**Useful Info**
 - <img src="https://noxxe.yells.wtf/r/377845659986090660.png">
 - Application Version: [e.g. 1.8]

**Additional context**

**Comment by maximmax42** [comment]
Most likely your antivirus preventing it from launching. Try to add `%appdata%\CustomRP` to exceptions.
