### ISSUE TITLE
CustomRP cannot be used with BetterDiscord.

### ISSUE THREAD

**Issue by unholfretka2137** [maximmax42/Discord-CustomRP#83]
**Describe the bug**
CustomRP cannot connect to Discord when BetterDiscord is installed

**To Reproduce**
1. Have BetterDiscord installed.
2. Try to connect CustomRP
3. See error "Connection Failed (Is Discord Running?)"

**Expected behavior**
CustomRP connects with BetterDiscord same way as with normal Discord.

**Useful Info**
 - Windows Version: Windows 10 21H2 Pro
 - Discord Version: Stable 108924
 - BetterDiscord Version: 1.3.0
 
 Please note that I didn't have any themes or plugins installed on BetterDiscord while using CustomRP.

**Comment by maximmax42** [comment]
But does it work if you uninstall BD?

**Comment by unholfretka2137** [comment]
> But does it work if you uninstall BD?

**Yes, it does**, but I was hoping it would also work with BD.

**Comment by maximmax42** [comment]
In that case I have no clue why it doesn't work. I assume games with rich presence work just fine?

**Comment by LowfiInaTrexSuit** [comment]
doesn't seem to work with goosemod either

**Comment by unholfretka2137** [comment]
> In that case I have no clue why it doesn't work. I assume games with rich presence work just fine?

Other rich presences work fine, even the Spotify one. Seems like CustomRP doesn't recognise BetterDiscord as just Discord and doesn't connect.

**Comment by maximmax42** [comment]
Which is weird, it should see it just fine. Unless the RPC library I use is to blame.

**Comment by unholfretka2137** [comment]
Alright I think I found the solution on how to fix it:
1. Backup your plugins and themes to another folder and remove them from BD's folders.
2. Repair BD from it's installer.
3. Move the backed up plugins and themes back to BD's folders.
4. Close and open Discord again.

Don't know how that did fix it, but it works. Closing.
