### ISSUE TITLE
add Streaming Option stats and URL

### ISSUE THREAD

**Issue by gaveer** [maximmax42/Discord-CustomRP#87]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
adding a streaming status option and URL button 
```
discordPresence.user.setActivity("Playing ", {
    type:"STREAMING",
    url: ""
});
```
**Describe alternatives you've considered**

**Additional context**

**Comment by maximmax42** [comment]
Not possible unless I ask the user for the token, which I'm not going to do.
