### ISSUE TITLE
Make if functional on Discord Canary (Or Multi account)

### ISSUE THREAD

**Issue by BoboJunior** [maximmax42/Discord-CustomRP#9]
**Is your feature request related to a problem? Please describe.**
I want to have both of my accounts displaying a RPC.

**Describe the solution you'd like**
Make if functional on Discord Canary (Or Multi account) useing tokens

**Describe alternatives you've considered**
Maybe the use of selecting the process id to inject in or something like that (im not a coder)

**Additional context**
Not really, just a multi-account rich present (Custom animated status maybe thats a push)

**Comment by maximmax42** [comment]
The app will connect to whichever Discord client was launched first, and only that. There is technically a way to connect to up to 10 Discord clients, but there's no easy way to find out how many clients are running, nor what pipes they're using. So while plausible, it'll be an absolute pain to implement and manage.

Also what do you mean animated status? If you mean animated images, Discord doesn't support that in presence.

**Comment by BoboJunior** [comment]
Yes, I mean animated status :)

**Comment by maximmax42** [comment]
Animated images? Yeah, not supported by Discord.

**Comment by BoboJunior** [comment]
No not animated images.  Theres something called animated status

**Comment by maximmax42** [comment]
Oh, oh I see. There's no way for my app to change the emoji status and no way to change the name of the discord application used in CustomRP either. I could technically animate the presence fields but you have to have the mini profile or full profile open for a while to see that.

**Comment by vilchu** [comment]
if that means that the status will change every x minutes, Discord hates API spam and is bannable.

**Comment by maximmax42** [comment]
Existing animated status plugin for BD has a minimum delay between "frames" of 3 seconds, but yeah, still not that practical.

**Comment by vilchu** [comment]
it's not supported in the BD server as it can you banned from discord ~~and also from BD server~~

**Comment by maximmax42** [comment]
Really? They ban from the server for using it? Why?

**Comment by vilchu** [comment]
Because it's not on official plugin list, and against Discord API terms or something

**Comment by maximmax42** [comment]
I mean, the entire BD is against TOS, although that plugin does ask the user for their token, so I guess that's fair.

**Comment by vilchu** [comment]
+ it causes API spam uwu
