### ISSUE TITLE
the custom rp only shows up for me

### ISSUE THREAD

**Issue by ZEHRIK** [maximmax42/Discord-CustomRP#90]
**BEFORE POSTING**
Please check https://github.com/maximmax42/Discord-CustomRP/wiki/FAQ for a possible solution. If it's not there, then carry on with creating an issue ticket.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Useful Info**
 - Windows Version: [e.g. Windows 7, Windows 10 2004]
 - Application Version: [e.g. 1.8]

**Additional context**

**Comment by maximmax42** [comment]
Do you have BetterDiscord installed?

**Comment by ZEHRIK** [comment]
yes

**Comment by maximmax42** [comment]
Yeah, for some reason my app doesn't play nicely with BD, and I can't figure out why. Try to reinstall BD, it helped in one case.

**Comment by ZEHRIK** [comment]
aight got it

**Comment by maximmax42** [comment]
Did it work?

**Comment by maximmax42** [comment]
No reply, so I assume it did. But if it didn't, comment again.
