### ISSUE TITLE
(no title)

### ISSUE THREAD

**Issue by FiberAhmed** [maximmax42/Discord-CustomRP#93]
[POEditor]
Can you delete the Arabic language and the Arabic language (Saudi Arabia)? It's annoying, just leave the Arabic (Egypt)

**Comment by maximmax42** [comment]
Sure. I was wondering why you created them in the first place if you never translated them properly. Was it just a mistake?

**Comment by FiberAhmed** [comment]
> Sure. I was wondering why you created them in the first place if you never translated them fully. Was it just a mistake?

Yes

**Comment by FiberAhmed** [comment]
> Sure. I was wondering why you created them in the first place if you never translated them fully. Was it just a mistake?

Yes, it is

**Comment by maximmax42** [comment]
Okay, deleted them.
