### ISSUE TITLE
Connection Error Wrong ID ( Eventho it is correct.

### ISSUE THREAD

**Issue by tama1299** [maximmax42/Discord-CustomRP#97]
I already tried to make a new application, even copied the id, tried to retype manually and it still didn't work. tried on on 1.13 n 1.14 still didn't work. please help, thank you

**Comment by maximmax42** [comment]
Can you send me the ID? I'll check it when I'll get on PC. In the meantime, try to use ID from the screenshot on the site/GitHub readme.

**Comment by tama1299** [comment]
hello sorry for the late reply. this is the id :936110221359718401

**Comment by maximmax42** [comment]
Yep, works for me. Do you have BetterDiscord by any chance? If yes, try to reinstall it. If not, try adding CustomRP to firewall exceptions.

**Comment by maximmax42** [comment]
Well uh, if the problem isn't fixed, comment again.
